---
- name: Install SQL Database Server on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - python3-pymysql
  when: ansible_distribution == "Ubuntu"

- name: Install SQL Database Server on CentOS
  dnf:
    name: "{{ item }}"
    state: present
    use_backend: dnf4
  loop:
    - mariadb-server
    - MySQL-python
  when: ansible_distribution == "CentOS"

- name: Start and enable the MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Secure MariaDB installation
  mysql_user:
    name: root
    host: localhost
    password: "2111419.!"
    state: present
    check_implicit_admin: yes
    login_user: root
    login_password: "2111419.!"
    login_unix_socket: "{{ mysql_unix_socket }}"
  vars:
    mysql_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Create OpenStack databases and users
  mysql_db:
    name: "{{ item.name }}"
    state: present
    login_user: root
    login_password: "2111419.!"
  with_items:
    - { name: 'keystone', collation: 'utf8_general_ci', encoding: 'utf8' }
    - { name: 'nova', collation: 'utf8_general_ci', encoding: 'utf8' }
    - { name: 'neutron', collation: 'utf8_general_ci', encoding: 'utf8' }
    - { name: 'glance', collation: 'utf8_general_ci', encoding: 'utf8' }

- name: Create OpenStack database users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.privileges }}"
    state: present
    login_user: root
    login_password: "2111419.!"
  with_items:
    - { name: 'keystone', password: '2111419.!', privileges: '*.*:ALL' }
    - { name: 'nova', password: '2111419.!', privileges: '*.*:ALL' }
    - { name: 'neutron', password: '2111419.!', privileges: '*.*:ALL' }
    - { name: 'glance', password: '2111419.!', privileges: '*.*:ALL' }
